name: QA Checks

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  qa-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Composer prepare
        run: composer update

      - name: Run tests
        run: |
          php -S localhost:8080 -t demo/web > /dev/null 2>&1 &
          vendor/bin/codecept build
          vendor/bin/codecept run
