name: QA Checks

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  qa-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
    steps:
      - name: Composer prepare
        run: |
          composer self-update && composer --version
          composer update --dev --prefer-dist --no-interaction

      - name: Run tests
        run: |
          php -S localhost:8080 -t demo/web > /dev/null 2>&1 &
          vendor/bin/codecept run
